# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  title: Carlos Torres, Data Scientist

# Second language
es:
  languageCode: es-pa
  contentDir: content/es
  title: Carlos Torres, Científico de Datos
  params:
    description:
  menu:
    main:
      - name: Sobre mí
        url: '#about'
        weight: 10
      - name: Experiencia
        url: '#experience'
        weight: 20
      - name: Proyectos
        url: '#projects'
        weight: 30
      - name: Publicaciones
        url: '#publications'
        weight: 40
      - name: Certificaciones
        url: '#accomplishments'
        weight: 50
      - name: Charlas
        url: '#talks'
        weight: 60
      - name: Contacto
        url: '#contact'
        weight: 70

# Second language
de:
  languageCode: de-de
  contentDir: content/de
  title: Carlos Torres, Data Scientist
  params:
    description:
  menu:
    main:
      - name: Über mich
        url: '#about'
        weight: 10
      - name: Erfahrung
        url: '#experience'
        weight: 20
      - name: Projekte
        url: '#projects'
        weight: 30
      - name: Veröffentlichungen
        url: '#publications'
        weight: 40
      - name: Zertifizierungen
        url: '#accomplishments'
        weight: 50
      - name: Vorträge
        url: '#talks'
        weight: 60
      - name: Kontakt
        url: '#contact'
        weight: 70
